# To build this test example with Java 1.1 VM, you will have
# to make following changes:
# (1) Set line 9 to be
#     JAVA2 = false
# (2) Change JDKDIR on line 15 to reflect the location of your 
#     JDK 1.1 VM
#

JAVA2 = true
APP_ROOT = ..
INC_ROOT = $(APP_ROOT)\include
LIB_ROOT = $(APP_ROOT)\lib

COPT = /GX -D_REENTRANT
JDKDIR = C:\Progra~1\Java\jdk1.5.0_12
CC = cl

!IF "$(JAVA2)" == "true"
JAVALIB = jvm.lib
!ELSE 
JAVALIB = javai.lib
!ENDIF

INCLUDES = -I$(JDKDIR)\include -I$(JDKDIR)\include\win32 -I$(INC_ROOT) 
CPPFLAGS = $(COPT) $(INCLUDES)
WMDIR = C:\SoftwareAG\webMethods8

all: test

test: test.cpp
	$(CC) $(CPPFLAGS) test.cpp /o test.exe /MT /link\
	/libpath:"$(JDKDIR)\lib" ..\lib\WinWMJni.lib $(JAVALIB)

runtest:
	SET JAVADIR=C:\Progra~1\Java\jdk1.5.0_12
	SET PATH=$(PATH);$(JDKDIR)\jre\bin\client;$(WMDIR)\IntegrationServer\sdk\cpp\lib
	SET CLASSPATH=$(CLASSPATH);$(JDKDIR)/jre/lib/rt.jar:$(JDKDIR)/lib/tools.jar;$(WMDIR)/common/lib/wm-isclient.jar;$(WMDIR)/common/lib/glassfish/gf.javax.mail.jar;$(WMDIR)/IntegrationServer/lib/wm-isserver.jar;
	test
clean:
	del *.pdb *.lib *.dll *.obj *.exp *.exe
